### ISSUE TITLE
How to add the function --kubeconfig if need to maintain multi deployment

### ISSUE THREAD

**Issue by mansonami** [samisalkosuo/kubeterminal#1]
Hi, 

Your tool is perfect to maintain the K8s.
But How to add the function --kubeconfig if need to maintain multi deployment

**Comment by samisalkosuo** [comment]
Hi,

Thanks! 

I added --kubeconfig option and kubeconfig-command to KubeTerminal. 

Usage:
`python kubeterminal.py --kubeconfig <path/to/kubeconfig> <another/path/to/kubeconfig>`

Within terminal kubeconfig-command lists kubeconfig files and they can be selected using `kubeconfig <index>`.

There's also  --current-kubeconfig option to select default kubeconfig file.

Changes are now in the dev-branch, so please take a look.

**Comment by samisalkosuo** [comment]
Change are now in the main-branch.
